### ISSUE TITLE
Error when running fs.connect()

### ISSUE THREAD

**Issue by dedayoa** [EvoluxBR/greenswitch#6]
Hello,
I just installed the latest pypi version (0.0.6) of greenswitch. I am running on Windows 10, Python 3.5.2.
While running through the example, doing a fs.connect() raises the error below:

`Traceback (most recent call last):
  File "C:\Users\Dayo\workspace\kitenv\lib\site-packages\gevent\greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\Users\Dayo\workspace\kitenv\lib\site-packages\greenswitch\esl.py", line 87, in receive_events
    self.handle_event(event)
  File "C:\Users\Dayo\workspace\kitenv\lib\site-packages\greenswitch\esl.py", line 125, in handle_event
    event.parse_data(data)
  File "C:\Users\Dayo\workspace\kitenv\lib\site-packages\greenswitch\esl.py", line 33, in parse_data
    headers[key.strip()] = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
<Greenlet at 0xc40670: <bound method InboundESL.receive_events of <greenswitch.esl.InboundESL object at 0x056827D0>>> failed with AttributeError`

Can you provide assistance on how to fix this.
Regards,

**Comment by italorossi** [comment]
FreeSWITCH version?

**Comment by dedayoa** [comment]
Version 1.6.12 -20-b91a0a6 64bit

I however install greenswitch on the Freeswitch host which is running debian 8, python 2.7.9 and all worked OK.

**Comment by italorossi** [comment]
I've tried here on Mac OS with Python 3.5.1 and it worked well

**Comment by dedayoa** [comment]
Well, I tried something else.
I installed greenswitch on a remote Debian7/Python 2.7.12 and got this error
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/greenswitch/esl.py", line 87, in receive_events
    self.handle_event(event)
  File "/usr/local/lib/python2.7/dist-packages/greenswitch/esl.py", line 125, in handle_event
    event.parse_data(data)
  File "/usr/local/lib/python2.7/dist-packages/greenswitch/esl.py", line 33, in parse_data
    headers[key.strip()] = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
<Greenlet at 0x7fa6c7e2bb90: <bound method InboundESL.receive_events of <greenswitch.esl.InboundESL object at 0x7fa6ca260ed0>>> failed with AttributeError`

It seems greenswitch only works if the host is localhost(127.0.0.1). Can you check this?

**Comment by dedayoa** [comment]
Hi, 
Sorry. After some more time, I realized this was not an issue. Problem was as a result of the wrong acl settings in event_socket.conf.xml
http://stackoverflow.com/a/37095859 was helpful.
